### ISSUE TITLE
Custom inbox tag does not get removed

### ISSUE THREAD

**Issue by kimdre** [stefanlachner/paperless-to-lexoffice#3]
When the script tries to remove the inbox id, it returns an error instead.

```
Check for new documents in paperless-ngx tagged for upload...
Search Results: [163]
Document #163 downloaded successfully.
Document has lexoffice UUID 75555819-7322-41bf-b97c-4e2d6d350435
Upload successful. Deleting file from tmp...
Error connecting to paperless-ngx, is it running? Error: list.remove(x): x not in list
```

Looking at the code it seems that the custom id of the inbox tag is not used and instead a hard-coded `[1]` is passed to the function.

https://github.com/stefanlachner/paperless-to-lexoffice/blob/65664dbc682d370df0ca9b37a664634ac0dca1af/source/paperless-search.py#L73-L73

**Comment by stefanlachner** [comment]
Thanks for pointing that out! Fix is already pushed to GitHub and Docker Hub (tag: latest).
